pipeline {
    agent {
        kubernetes {
            yaml '''
                apiVersion: v1
                kind: Pod
                metadata:
                    name: jenkins-agent-pod
                    labels:
                        app: jenkins-agent
                spec:
                    containers:
                        -   name: git
                            image: alpine/git:latest
                            command:
                                - sleep
                            args:
                                - 99d
                            tty: true

                        
                        -   name: kaniko
                            image: gcr.io/kaniko-project/executor:debug
                            command:
                                - /busybox/sleep
                            args:
                                - 99999

                            tty: true
                        
                        -   name: mailer
                            image: alpine:latest
                            command:
                                - sleep
                            args:
                                - 99d
                            tty: true
            '''
        }
    }
    environment {
        GIT_REPO = 'https://github.com/mohamedbstar413/go-app-repo.git'
        GIT_BRANCH = 'main'
        DOCKER_IMAGE = 'bstar999/iti-gp-back-image'
        DOCKER_TAG = "${env.BUILD_NUMBER}"
        
    }
    stages {
        stage('Checkout') {
            steps {
                container('git') {
                    sh "git clone -b $GIT_BRANCH $GIT_REPO"
                }
            }
        }
        stage('Build docker image and push to docker hub') {
            steps {
                withCredentials([usernamePassword(
                            credentialsId: 'dockerhub',
                            usernameVariable: 'DOCKER_USER',
                            passwordVariable: 'DOCKER_PASS'
                        )]) {
                            container('kaniko') {
                        sh """
                        cat > /kaniko/.docker/config.json <<EOF
                        {
                            "auths": {
                                        "https://index.docker.io/v1/": {
                                            "auth": "\$(echo -n $DOCKER_USER:$DOCKER_PASS | base64 | tr '\n')"
                                        }
                            }
                        }
                        EOF
                        /kaniko/executor \
                            --context `pwd`/application-code/backend \
                            --dockerfile Dockerfile \
                            --destination $DOCKER_IMAGE:$DOCKER_TAG \
                            --destination $DOCKER_IMAGE:latest \
                            --cache=true \
                            --verbosity=info \
                            --snapshot-mode=redo
                    """
                            }
                        }
            }
        }
        
        stage('Send Email') {
            steps {
                container('mailer') {
                    withCredentials([usernamePassword(credentialsId: 'gmail', usernameVariable: 'GMAIL_USER', passwordVariable: 'GMAIL_PASS')]) {
                        sh """
                    apk add --no-cache curl ca-certificates

                    FROM="mabdelsattar413@gmail.com"
                    TO="mabdelsattar413@gmail.com"
                    SUBJECT="Build \$BUILD_NUMBER completed"
                    BODY="Job: \$JOB_NAME\\nBuild URL: \$BUILD_URL\\nStatus: \$currentBuild.currentResult"

                    echo "Sending email..."
                    echo -e "From: \$FROM\\nTo: \$TO\\nSubject: \$SUBJECT\\n\\n\$BODY" > /tmp/email.txt

                    curl --url "smtps://smtp.gmail.com:465" \
                         --ssl-reqd \
                         --mail-from "\$FROM" \
                         --mail-rcpt "\$TO" \
                         --upload-file /tmp/email.txt \
                         --user "\$GMAIL_USER:\$GMAIL_PASS" \
                         --verbose
                """
                    }
                }
            }
        }
    }
}