apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-application
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/mohamedbstar413/iti-graduation-project.git
    targetRevision: main
    path: argocd/argocd-applications
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
