apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipPrune=false
    argocd.argoproj.io/compare-options: IgnoreNormalizedCRDs=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.jenkins.io
    chart: jenkins
    targetRevision: 5.1.0          # stable chart version
    helm:
      releaseName: jenkins
      values: |
        # Persistent storage
        persistence:
          enabled: true
          existingClaim: jenkins-pvc

        # Jenkins controller configuration
        controller:
          runAsUser: 1000
          fsGroup: 1000
          adminUser: admin
          adminPassword: admin

          # Custom init container to fix permissions
          additionalInitContainers:
            - name: fix-jenkins-home
              image: busybox:1.36
              command: ["sh", "-c"]
              args:
                - |
                  echo "Fixing permissions on /var/jenkins_home ..."
                  chown -R 1000:1000 /var/jenkins_home
                  chmod -R 775 /var/jenkins_home
                  echo "Done!"
              volumeMounts:
                - name: jenkins-home
                  mountPath: /var/jenkins_home
              securityContext:
                runAsUser: 0
                runAsGroup: 0
                allowPrivilegeEscalation: true

          # Optional: set Jenkins URL if needed
          jenkinsUrl: http://jenkins.jenkins.svc.cluster.local:8080

  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
